language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_success:
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git clone "https://${GH_TOKEN}@${GH_REF}"
  - cp -rf dist/* yolkpie.github.io/yolk-cli/
  - cd ./yolkpie.github.io
  - git add .
  - git commit -m 'travis-ci auto build yolk-cli'
  - git push origin "${P_BRANCH}"
  - cd ../
  - git clone "https://${U_NAME2}:${CO_TOKEN}@${CO_REF}"
  - cp -rf dist/* yolkpie.github.io/yolk-cli/
  - cd ./yolkpie.github.io
  - git add .
  - git commit -m 'travis-ci auto build yolk-cli'
  - git push origin "${P_BRANCH}"
branches:
  only:
    - master