language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - git clone "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  - npm run build
after_success:
  - cd ./yolkpie.github.io
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add -A
  - git commit -m 'deploy'
  - git push --quiet --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}